### PR TITLE
Add F3 logo

### PR DESCRIPTION
**Pull request by error401de**
Preparation for issue https://github.com/geokrety/geokrety-website/issues/502
Please review, thanks!

### CODE REVIEW

**Comment by kumy** [comment]
Thanks! But we prefer using `.svg` files when available, @error401de may you change the logo please :)

**Comment by error401de** [comment]
Hi @kumy ,
its changed, please review :)

**Comment by kumy** [comment]
Thanks!

**Comment by kumy** [comment]
I missed that, but those commits should have been squashed together ;)

**Pull request merged**
